

CREATE TABLE `webcams_host` (
  `id` int(13) unsigned NOT NULL AUTO_INCREMENT,
  `status` enum('approved','waiting','closed') DEFAULT 'waiting',
  `host_id` int(19) unsigned DEFAULT NULL,
  `user` varchar(20) NOT NULL,
  `pass` varchar(20) NOT NULL,
  `firstname` varchar(64) DEFAULT NULL,
  `lastname` varchar(64) DEFAULT NULL,
  `address1` varchar(128) DEFAULT NULL,
  `address2` varchar(128) DEFAULT NULL,
  `city` varchar(64) DEFAULT NULL,
  `state` varchar(10) DEFAULT NULL,
  `postcode` varchar(10) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `age` int(4) DEFAULT '0',
  `pref` varchar(64) DEFAULT NULL,
  `local` varchar(128) DEFAULT NULL,
  `likes` varchar(100) DEFAULT NULL,
  `dislikes` varchar(100) DEFAULT NULL,
  `bio` varchar(2048) DEFAULT NULL,
  `chat` varchar(256) DEFAULT NULL,
  `languages` mediumtext DEFAULT NULL,
  `category` mediumtext DEFAULT NULL,
  `schedule` varchar(1000) DEFAULT NULL,
  `timezone` varchar(128) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `max_time` int(13) DEFAULT '3',
  `max_time_total` int(13) DEFAULT '15',
  `max_time_total_period` int(13) DEFAULT '1440',
  `mode1` tinyint(2) DEFAULT '1',
  `mode2` tinyint(2) DEFAULT '1',
  `mode3` tinyint(2) DEFAULT '1',
  `allow_guest` tinyint(2) DEFAULT '1',
  `pay2` int(13) DEFAULT '199',
  `pay3` int(13) DEFAULT '299',
  `com2` int(3) DEFAULT '50',
  `com3` int(3) DEFAULT '60',
  `tip_com2` int(3) DEFAULT '35',
  `tip_com3` int(3) DEFAULT '50',
  `max_streams` int(13) DEFAULT '5',
  `view_user_bal` tinyint(2) DEFAULT '1',
  `profile` tinyint(2) DEFAULT '1',
  `media` tinyint(2) DEFAULT '1',
  `stats` tinyint(2) DEFAULT '1',
  `aim_user` varchar(255) DEFAULT NULL,
  `aim_pass` varchar(255) DEFAULT NULL,
  `pos_bias` int(13) DEFAULT '5',
  `allow_ban` tinyint(2) DEFAULT '0',
  `aux_link1_url` varchar(255) DEFAULT NULL,
  `aux_link1_txt` varchar(255) DEFAULT NULL,
  `aux_link2_url` varchar(255) DEFAULT NULL,
  `aux_link2_txt` varchar(255) DEFAULT NULL,
  `aux_link3_url` varchar(255) DEFAULT NULL,
  `aux_link3_txt` varchar(255) DEFAULT NULL,
  `studio_id` int(13) DEFAULT '1000',
  `chat_only` tinyint(2) DEFAULT '0',
  `created` int(13) DEFAULT '0',
  `updated` int(13) DEFAULT '0',
  `actioned` int(13) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webcams_pivot` (
  `pid` int(13) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('user','host','studio') NOT NULL,
  `id` int(13) unsigned NOT NULL,
  `uid` int(13) DEFAULT '0',
  `ip` varchar(128) DEFAULT NULL,
  `netaddr` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webcams_studio` (
  `id` int(13) unsigned NOT NULL AUTO_INCREMENT,
  `status` enum('approved','waiting','closed') DEFAULT 'waiting',
  `studio_id` int(19) unsigned DEFAULT NULL,
  `studioname` varchar(128) DEFAULT NULL,
  `firstname` varchar(64) DEFAULT NULL,
  `lastname` varchar(64) DEFAULT NULL,
  `address1` varchar(128) DEFAULT NULL,
  `address2` varchar(128) DEFAULT NULL,
  `city` varchar(64) DEFAULT NULL,
  `state` varchar(10) DEFAULT NULL,
  `postcode` varchar(10) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `enabled` tinyint(2) DEFAULT '1',
  `pos_bias` int(6) DEFAULT '1',
  `allow_create_host` tinyint(2) DEFAULT '1',
  `com2` decimal(10,2) DEFAULT '0.00',
  `com3` decimal(10,2) DEFAULT '0.00',
  `tip2` decimal(10,2) DEFAULT '0.00',
  `tip3` decimal(10,2) DEFAULT '0.00',
  `created` int(13) DEFAULT NULL,
  `updated` int(13) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `webcams_user` (
  `id` int(13) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(19) unsigned DEFAULT NULL,
  `user` varchar(20) DEFAULT NULL,
  `pass` varchar(20) DEFAULT NULL,
  `firstname` varchar(64) DEFAULT NULL,
  `lastname` varchar(64) DEFAULT NULL,
  `address1` varchar(128) DEFAULT NULL,
  `address2` varchar(128) DEFAULT NULL,
  `city` varchar(128) DEFAULT NULL,
  `state` varchar(10) DEFAULT NULL,
  `postcode` varchar(10) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `created` int(13) DEFAULT NULL,
  `updated` int(13) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

